# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         REST-Application
version:      0.93
version_from: lib/REST/Application.pm
installdirs:  site
requires:
    CGI:                           0
    Tie::IxHash:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
